export const FETCH_PROGRAM_TYPES_PENDING = 'FETCH_PROGRAM_TYPES_PENDING';
export const FETCH_PROGRAM_TYPES_SUCCESS = 'FETCH_PROGRAM_TYPES_SUCCESS';
export const FETCH_PROGRAM_TYPES_FAILURE = 'FETCH_PROGRAM_TYPES_FAILURE';
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
